//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourPlan
    {
        public int tourPlanId { get; set; }
        public string attractionDetails { get; set; }
        public Nullable<System.DateTime> geneateTime { get; set; }
        public Nullable<int> price { get; set; }
        public string calendar { get; set; }
        public Nullable<int> preferenceID { get; set; }
        public Nullable<int> guideId { get; set; }
        public Nullable<int> attractionId { get; set; }
    
        public virtual attraction attraction { get; set; }
        public virtual guide guide { get; set; }
        public virtual userPreference userPreference { get; set; }
    }
}
